version: '3'
services:
  minecraft:
    build: .
    container_name: minecraft-paper-server
    ports:
      - "25565:25565"
      - "8123:8123"
    environment:
      - MEMORY=8G
      - ACCEPT_EULA=true
      - MINECRAFT_VERSION=1.21.4